NAME: Priya Gawhane

Create a Linear Regression model using Python/R to predict home prices using Boston Housing dataset (kaggle link: https://www.kaggle.com/datasets/altavish/boston-housing-dataset?resource=download)
The Boston housing dataset contains information about various houses in Boston through different parameters.There are 506 samples and 14 feature variables in this dataset.
The objectives is to predict the value of prices of the house using the given features

In [2]:
#importing the dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("HousingData.csv")

In [6]:
df.head(8)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,NaN,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1

In [7]:
df.tail(8)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6,391,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [8]:
df.shape

(506, 14)

In [9]:
#checking the missing values
df.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.shape

(394, 14)

In [12]:
#again checking the missing values
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

Defining the dependent and independent variables

In [16]:
X = df.drop(['MEDV'], axis = 1)
Y = df['MEDV']

In [17]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48

In [18]:
Y

0      24.0
1      21.6
2      34.7
3      33.4
5      28.7
       ...
499    17.5
500    16.8
502    20.6
503    23.9
504    22.0
Name: MEDV, Length: 394, dtype: float64

Importing the dependecies for LinearRegression model

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

Splitting the data into Train and Test

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20,random_state=42)

In [35]:
print(X.shape, X_train.shape, X_train.shape)

(394, 13) (315, 13) (315, 13)

Model fitting and implementation

In [36]:
model = LinearRegression()

In [37]:
model.fit(X_train, Y_train)

LinearRegression()

In [38]:
#Accuracy on training data
X_train_prediction = model.predict(X_train)

In [39]:
print(X_train_prediction)

[16.81932746 37.49180585 24.47922111 24.240256   12.62395446 29.03521242
 20.75233173 16.02447343 11.80811628 39.54348884 38.7705204  20.71839121
 18.71563247 27.67746356 15.89558614 26.88829012 39.13725109 30.73716318
 22.61323814 21.24607354 12.91875902 21.80613926 30.63354941 19.90754685
 14.13372731 15.94134163 16.53681865 20.20924399 15.22373493 37.84836536
 13.63296132  5.21892453  1.46345053 26.1339478  26.71224006 20.04923854
 11.99417375 24.65041922 31.29062752 19.05650777 17.48099562 11.94084658
 19.35977847 13.51285883 11.93813401 31.11666541 32.62174548 24.71266959
 23.18622169 34.70581204 15.65842663 21.60979659 24.22597311 13.45656306
 21.38038503 38.52927303 22.66185868 22.36591378  6.13658771 26.00352351
 10.8856519  22.99133496 27.70053486 14.94774747 21.17783463 13.28650136
 11.04713871 25.9055865  13.24483591 15.943177    2.00117    19.24995713
 33.97874557 20.85497941 24.81213463 35.43415375 33.34532999 10.02504524
 25.35097619 13.40165345 13.75433994 18.34309997 18.86049578 32.91599872
 14.60484326 22.1670433  26.22765656 17.79570986 20.71027755 30.97195154
 12.8673003  20.80661032 28.07095595 26.53955544 15.03176703 23.45797953
 32.66772839 15.60672199 28.56429799 20.2348176  11.83987974 21.45890195
 11.88417787 21.43512867 21.82564335 27.63942189 26.72449586 25.22493727
 13.69740912 22.56520692  9.60028652 24.72551799 25.16228088 17.99482152
 30.62844852 25.54087689 17.98965855 32.66004579 14.61056269 30.81408926
 22.63869768 19.07939485 21.42912819 32.08791581 18.1880077  17.53560812
 31.66125861  6.10455019 20.07908367  5.96872952 17.84040503 25.5820659
 12.13131433 17.70476887 19.11103395 23.4695956  24.35883436 26.28108932
 32.02260865 37.57135449 31.11777984 14.83671726 30.41316892 36.75201646
 16.82808566 34.38505515 29.31608528 12.23718249 10.22491353  5.73961759
 27.1651046  20.89084923 20.29803481  6.77437832 13.33340236 27.71883046
 30.00130729 13.51877213 14.43727765 35.6183393   6.73265435 14.2746494
 15.09824301 22.72069439 24.68876664 20.24558194 25.10030148 35.61709588
 16.0924113  16.45550303 23.70791371  6.75334312 24.2277347  24.86325792
 28.56105922 24.97061878 31.26868762 20.703329   29.04118884 10.61692179
 26.39725685 25.854291   19.86908252  7.37084433 44.60808703 26.26917155
 18.02036084 26.5102629  14.1373988   3.26566122 39.45722098 17.94558598
 16.74421918 35.33296245 23.94938811  4.99136782 24.9039893  21.95715797
 15.23578442 22.37057545 33.25293564 16.1192583  35.19083523 28.03285434
 24.66617813 33.41643345 22.6541884  32.80160111 23.46359834 30.72052443
 43.16618461 17.74825481 17.56912218 19.31113685 27.58763766 21.7105162
 31.19595708 42.26822948 18.16575879 23.74582396 25.14385785 25.925643
 24.77176515 21.60368454 22.94048405  8.36816435 16.60840472 33.52028185
 10.98569339 16.38066981 12.55943766 35.01620463 20.75175094  8.83377405
 32.05629624 27.97625161 28.39218562 16.26784759 20.80637928 19.15442225
 21.30676547  9.14246779 13.24403112 27.51861382 35.80528514 37.7845689
 28.13378855 30.61166427 20.34950289 15.39737338 22.16204941 15.22846336
 22.93413738 24.8261892  20.91392828 28.53301206 34.37139357 34.32234114
 19.25786974 20.61034492 13.69287516 23.26746478 22.39350101 22.81825327
 17.02644583  7.50016441 20.98204072 27.80808242 17.32034991 18.26046996
 19.21123745 36.45715321  9.45689757 20.3422441  16.38288494 25.03816697
 23.75150972 17.74136703 23.68556998 15.9427194  22.04825009 24.46495645
 14.59494865 18.18422077 21.82799148 11.18351745 34.98085201 25.14143238
 13.47359852 17.63267427 29.42961883 25.39755191 19.3854559  19.90784445
 17.31915293 25.07673256 18.65256839 25.0323675  35.68395508 32.42348236
 19.46922715 23.1223713  25.47450909 19.2397014  16.91471966 35.26760406
 13.77256149 25.46994546 15.7170896  27.95393861 25.20777751 19.01362672
 17.09906224 16.57668788 21.00462746]

Checking the model score

In [42]:
model.score(X_test,Y_test)

0.627084994167318